<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RetakeV4.Contracts</RootNamespace>
    <AssemblyName>RetakeV4.Contracts</AssemblyName>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RetakeV4" />
    <InternalsVisibleTo Include="RetakeV4.Integration.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.370">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
